### ISSUE TITLE
how to use a SMPPEX.SimpleClient module

### ISSUE THREAD

**Issue by gac** [savonarola/smppex#1]
hi, i am using a SMPPEX.SimpleClient module to try to send a smpp message to SMPPSim simulator

the call to create function is sucessfully, this function return a pid and a ref 

but how can i call send_pdu function?

the send_pdu function receive a session as parameter but how i obtain this session?

thank you.

**Comment by savonarola** [comment]
Hello!

`SMPPEX.SimpleClient` isn't a general-purpose client, it's a demonstration of use of very low level `SMPPEX.Session` module. The only responsibility of `SMPPEX.Session` is converting raw data stream to SMPP PDUs, it does not handle sequence ids, timers etc.

In general, currently there are too few tools in this library for client usage. The api of modules is also unstable.
