### ISSUE TITLE
Unbind/Graceful shutdown

### ISSUE THREAD

**Issue by archSeer** [savonarola/smppex#20]
One more case we've ran into while stress testing!

SMPP supports an unbind operation (either SMSC or ESME are allowed to send it), signalling a "log off" of sorts. It's the correct way to signal session termination without relying on enquire_link timeouts.

**Scenario**: We're connecting to an upstream SMSC via our ESME implementation. The upstream SMSC has a connection limit (max 8 connections), and we're running 8 connections. Any connections after that receive an error.

We decide to do a new deploy. Old connections are terminated, but the SMSC won't detect them as dead until the next enquire_link (15-45s). If we try opening new connections now, we will receive errors, and the upstream will also be trying to send messages to those dead connections (until it sees the node died and schedule a retry).

The solution here is to send an `unbind` pdu (and since SMPPEX is async preferably wait for a resp). We tried to do that inside `handle_stop`: 

```diff
@ esme.ex:44 @ defmodule ESME do

   def handle_resp(pdu, original_pdu, st) do
     case Pdu.command_name(pdu) do
+      :unbind_resp ->
+        send self(), :unbound
@ esme.ex:161 @ defmodule ESME do

   def handle_stop(st) do
+    send_unbind
+    receive do
+      :unbound -> nil
+    after
+      5_000 -> nil
+    end
   end
```

Problem with this is that the socket is closed just before handle_stop, and it's impossible to determine if the socket died, or if we're just gracefully shutting down.

**Possible solution**: For a graceful GenServer shutdown (we're using distillery + SIGTERM, it will call `:init.stop` for us), you'd normally do `Process.flag(:trap_exit, true)` inside `init`, which will make it call `def terminate(reason, status)`.

Maybe making SMPPEX.ESME/MC implement `terminate` that calls our module's `terminate` would work fine? Hopefully that will be called before `handle_stop` terminates the socket, but I'm not sure if that will work with MC since it uses ranch connections.

---

I know I've piled up a few issues now, so if the solution above sounds fine, I can go ahead and try implementing it! I'm just not sure what the most semantic solution would be, so I figured I'd open up a discussion first

**Comment by savonarola** [comment]
Hello!

The whole problem seems quite complicated to me.

As far as I can see, the proposed solution shouldn't work: when the ESME GenServer is waiting for an `:unbound` message it cannot handle resps with `handle_resp` callback. The session handler will fail with timeout.

That reveals the roots of the problem: ESME GenServer should proceed with some kind of dialog (sending `unbind` and receiving `unbind_resp`) for graceful disconnect. This part of dialog requires a functioning ESME and this contradicts to the idea to handle it within a single callback (either `terminate` or `handle_stop`).

So my variant of graceful shutdown would be like the following:
* Implement `unbind` function for ESME which sends `unbind` packet.
* Implement an additional case in `handle_resp` which calls `ESME.stop` on receiving `unbind_resp`.
* Implement a wrapper GenServer which launches ESME server and handles terminates calling `unbind` when terminating.

**Comment by archSeer** [comment]
Ah right...

Hmm, that would sort of work! We should probably implement this inside the library? That means one extra process per connection though, but I guess it's fine -- usually people will only have a few (tens) of ESME.

How would this work with the MC then? I guess that the term signal travels down the process tree, so it would be fine, the MC would just need to block until all connections unbind_resp

**Comment by archSeer** [comment]
Here's a working implementation for the ESME! I would love it if we could somehow include this in the library itself, as there's a lot of gotchas in implementing this correctly.

```elixir
defmodule ESME.Server do
  @moduledoc """
  A wrapper around Rxtx that traps exits and will handle graceful shutdown.

  We need the wrapper because of the async nature of the Rxtx (we want to send
  an unbind and block until we get a resp pdu).
  """
  use GenServer

  defstruct [ :child_pid, :config ]

  def start_link(opts) do
    GenServer.start_link(__MODULE__, opts)
  end

  def init(opts) do
    Process.flag(:trap_exit, true)
    {:ok, pid} = ESME.Rxtx.start_link(opts, self())
    {:ok, %__MODULE__{child_pid: pid, config: opts}}
  end

  # if we're terminating because the child unbound, skip the unbind
  def terminate(:unbind, state), do: nil

  def terminate(reason, state) do
    # 1) send unbind via esme
    SMPPEX.ESME.cast(state.child_pid, :unbind)
    # 2) wait for unbind_resp
    receive do
      :unbound -> :ok
    after # or timeout
      4_000 -> :timeout
    end
    # 3) stop rxtx
    SMPPEX.ESME.stop(state.child_pid)
  end

  # if the child exits, shutdown
  def handle_info({:EXIT, pid, _reason}, %{child_pid: pid, config: opts} = st) do
    {:stop, :unbind, st}
  end
end

defmodule ESME.Rxtx do
  use SMPPEX.ESME
  alias SMPPEX.Pdu
  alias SMPPEX.Pdu.{Factory, Errors}

  defstruct [ config: nil, parent_pid: nil  ]
  @type t :: %__MODULE__{}

  @spec start_link(opts :: config, parent :: pid) :: GenServer.on_start
  def start_link(%{host: host, port: port} = opts, parent \\ nil) do
    SMPPEX.ESME.start_link(host, port, {__MODULE__, [opts, parent]}, [enquire_link_limit: 45_000, response_limit: 20_000])
  end

  @spec init([term]) :: {:ok, __MODULE__.t}
  def init([%{system_id: system_id, password: password} = opts, parent]) do
    SMPPEX.ESME.send_pdu(self(), Pdu.Factory.bind_transceiver(system_id, password))
    {:ok, %__MODULE__{config: opts, parent_pid: parent}}
  end

  @spec handle_pdu(SMPPEX.Pdu.t, __MODULE__.t) :: __MODULE__.t
  def handle_pdu(pdu, st) do
    case Pdu.command_name(pdu) do
      :enquire_link ->
        SMPPEX.ESME.reply(self(), pdu, Pdu.Factory.enquire_link_resp)
        st
      :unbind ->
        SMPPEX.ESME.reply(self(), pdu, Pdu.Factory.unbind_resp)
        # we don't stop here but in pdu send result to ensure that the resp is transmitted
        st
    end
  end

  @spec handle_resp(SMPPEX.Pdu.t, SMPPEX.Pdu.t, __MODULE__.t) :: __MODULE__.t
  def handle_resp(pdu, original_pdu, st) do
    case Pdu.command_name(pdu) do
      :enquire_link_resp -> st
      :unbind_resp ->
        # tell the parent we finished unbind
        send st.parent_pid, :unbound
        st
    end
  end

  def unbind do
    SMPPEX.ESME.send_pdu(self(), Pdu.Factory.unbind())
  end

  def handle_cast(:unbind, st) do
    unbind()
    st
  end

  # once unbind_resp has been sent, shut down
  # command_id: 0x80000006 == unbind resp
  @unbind_resp_id 0x80000006
  def handle_send_pdu_result(%Pdu{command_id: @unbind_resp_id}, _result, st) do
    SMPPEX.ESME.stop(self())
    st
  end
end

```


I'm having problems implementing this same functionality for the SMSC though, at least without modifying the library itself. The listener processes are supervised by the ranch supervisor (ranch_conns_sup), and there's currently no way to do a start_link on that (I need a process above either MC or all of the open connections, so that I can trap the exit there and then gracefully shutdown) 

---

Semi-related: I also think we should consider providing a default implementation for enquire_link (just returns resp), since that's what almost every server will need to do (we should also consider some defaults elsewhere? -- if we add unbind, the above would be a resonable default).

**Comment by savonarola** [comment]
Hello!

I greatly appreciate the introduced contribution, and it seems to me that the proposed functionality is worth integrating into library.

Currently I am thinking about the way it should be integrated, i.e. how should "not so barebone" ESME/MC look :)

**Comment by savonarola** [comment]
Hello!

There have been some important changes in SMPPEX API recently. Now it is more `GenServer` compliant, so ESME sessions are just simple `GenServer`s and have `terminate` callback.

`terminate` callback can return a list of last PDUs to be send into the socket before process termination. For example, one can send an `unbind` PDU before termination. Can this solve the original problem?

**Comment by archSeer** [comment]
Not really :/ when we send `unbind`, we're supposed to wait for `unbind_resp`, then unbind. The only time we can do this is when the user sends `unbind`, then after we send `unbind_resp` we can immediately unbind.

By the way, I wanted to try the v2 branch, but the ranch dependency is too strict. Using plug with cowboy depends on ranch 1.3, meanwhile smppex depends on 1.4:

```
Failed to use "ranch" (version 1.3.2) because
  cowboy (version 1.1.2) requires ~> 1.3.2
  smppex (version 2.0.1) requires ~> 1.4
```

**Comment by savonarola** [comment]
Hello, I have loosened `ranch` requirements for v2 in 2.2.1

Still considering the issue, but now we seem to have a more reliable basis (a finer api) for solving it :)

**Comment by savonarola** [comment]
Hello! There is an example implementation of ESME graceful shutdown in https://github.com/savonarola/smppex_graceful repo. MC graceful shutdown can be implemented in much the same way.

I feel that this code is better to be kept as a demo, since there can be different views on organizing sessions.

Also, enquire_link's are completely automatic in > 2.2.
