### ISSUE TITLE
v2 drops handle_parse_error_support.

### ISSUE THREAD

**Issue by archSeer** [savonarola/smppex#32]
As specified in https://github.com/savonarola/smppex/pull/30, I'd prefer to be able to override the default behavior and handle parse errors by myself (dropping the pdu) instead of automatically stopping my ESME/SMSC.

Our current behavior is we ACK the pdu based on the header, drop it and just keep on going. If we just immediately cut the session, the carrier will just retry the same pdu (and then we stop again -- it's continually killing our session every minute or two). 

In v1, we did:

```elixir
 def handle_parse_error({:unparsed_pdu, raw_pdu, reason}, st) do
    Logger.warn(state: :parse_error, reason: inspect(reason), pdu: inspect(raw_pdu, limit: :infinity))

    command_id = 0x80000000 + raw_pdu.command_id
    code = Errors.code_by_name(:RINVTLVLEN) # TODO: expand to handle more flexibly
    resp = Pdu.new({command_id, code, 0})
    SMPPEX.ESME.reply(self(), raw_pdu, resp)
    {:ok, st}
end
```

But [v2 drops support for that](https://github.com/savonarola/smppex/blob/dff5272a6592bcbfe444b7039908008ef6dd1ddf/lib/smppex/transport_session.ex#L248)

**Comment by archSeer** [comment]
Ah, that's now `handle_unparsed_pdu`?

**Comment by savonarola** [comment]
Yes %)

**Comment by archSeer** [comment]
Hmm okay, one more question: . How come the `handle_send_pdu_result` returns `st` instead of `{:ok, st}`? It seems inconsistent with all the other callbacks now which take `{:ok, st}`.

I'll leave some more feedback as we complete our migration 👍

**Comment by savonarola** [comment]
>How come the handle_send_pdu_result returns st

This was made on purpose, because `handle_send_pdu_result` can be called while a sequence of messages is sent by `TransportSession`. It would be very confusing to interrupt or extend this sequence with new messages (like other callbacks do), so I chose to receive only new state from `handle_send_pdu_result`.

**Comment by archSeer** [comment]
Hmm okay, but I'd at least make the response `{:ok, st}` (without `{:ok, [pdus], st}`) -- that way it matches all the other responses, won't break backwards compatibility if you decide to support other responses than just updating the state in the future

**Comment by archSeer** [comment]
We had to revert our rollback of v2, both `smsc` and `esme` are continually failing with `:socket_closed`/`:tcp_closed`.

**Comment by archSeer** [comment]
Fixed by using

```elixir
  def handle_socket_closed(st), do: {:normal, st}
```

to silence the errors. We're now running v2 in prod, cheers! 🎊

**Comment by savonarola** [comment]
Great!
