### ISSUE TITLE
Don't use GenServer labels in TransportSession

### ISSUE THREAD

**Issue by edescourtis** [savonarola/smppex#39]
I am trying to add process instances of `TransportSession` to [Swarm](https://github.com/bitwalker/swarm) this library assumes that I can implement handle_call() with the [:'$gen_call'](https://github.com/erlang/otp/blob/4f91c8a34f4cc2c728a63e8d218566b3b3795b10/lib/stdlib/src/gen_server.erl#L210) label for a message it sends me. It seems to me that you should be using [:gen.call](https://github.com/erlang/otp/blob/4f91c8a34f4cc2c728a63e8d218566b3b3795b10/lib/stdlib/src/gen.erl#L152) with your own label inside the TransportSession module instead of using the GenServer label. This would avoid compatibility issues with other libraries. The user supplied module would then handle all :'$gen_call' and [:'$gen_cast'](https://github.com/erlang/otp/blob/4f91c8a34f4cc2c728a63e8d218566b3b3795b10/lib/stdlib/src/gen_server.erl#L246) requests.

**Comment by edescourtis** [comment]
At the very least it should forward all unknown requests to the user module.

**Comment by edescourtis** [comment]
I submitted a pull request

**Comment by savonarola** [comment]
Hello!

This is solved with #42 as far as I can see.
