### ISSUE TITLE
TLV fields

### ISSUE THREAD

**Issue by sergey-chechaev** [savonarola/smppex#43]
Hello.

How I can set optional TLV field 0x3004 value 2 type integer uint8 for PDU – it means service SMS?

**Comment by savonarola** [comment]
Hello!

0x3004 isn't a standard SMPP TLV field, so one should convert its value to binary oneself:

```
SMPPEX.Pdu.Factory.submit_sm("FROM", "71234567890", "hello!") 
|> SMPPEX.Pdu.set_optional_field(0x3004, << 2 >>) 
```

**Comment by sergey-chechaev** [comment]
Yah, it works!
