### ISSUE TITLE
Generic nack - recognized as pdu - not as pdu response

### ISSUE THREAD

**Issue by beirutheisenberg** [savonarola/smppex#58]
https://github.com/savonarola/smppex/blob/1c8dbd9673291431b2d329a2cb20134c91857af2/lib/smppex/pdu.ex#L375

Hi - I would like to ask if generic_nack is on purpose recognized as PDU - not response PDU?

Usually, I receive it as a response to malformed PDU (wrong length, unsupported command id)  and currently when I receive generic nack as a response it arrives as incoming PDU - not PDU resp and PDU times out. Would it be possible to handle it as a response - or there is reasoning why generic nack is not recognized as a response?

KR

**Comment by savonarola** [comment]
Hello!

I considered obtaining `generic_nack` from the other peer be an extraodinary situation: when one of the peers does not implement SMPP 3.4 properly.

Also, in general, `generick_nack` may not include `sequence_id` identifying  malformed pdu, and it would be odd to
* implement handling of `generick_nack` in two places: as a response for a pdu and as a "standalone" pdu;
* implement expectation of `generick_nack` as a possible response for each sent pdu.

**Comment by beirutheisenberg** [comment]
Hello,
Tnx a lot 👍
