### ISSUE TITLE
Why is the IF Version not sended?

### ISSUE THREAD

**Issue by Menkir** [savonarola/smppex#61]
Hi @savonarola ,
i know that smppex only supports smpp 3.4. In e.g transmitter_bind the version isn't set by smppex.

![image](https://user-images.githubusercontent.com/15153427/67868277-086ced80-fb2c-11e9-8550-0a461b29e0fa.png)

That's a problem because i need to talk with another smpp server which checks the version. According to the docs there is no possibility to set the version manually.

**Comment by savonarola** [comment]
Hello!

One can set `interface_version` in this way:
```
iex(4)> SMPPEX.Pdu.Factory.bind_transmitter("system_id", "password") |> SMPPEX.Pdu.set_mandatory_field(:interface_version, 0x34) 
%SMPPEX.Pdu{
  command_id: 2,
  command_status: 0,
  mandatory: %{
    interface_version: 52,
    password: "password",
    system_id: "system_id"
  },
  optional: %{},
  ref: #Reference<0.4205070554.1013710852.168993>,
  sequence_number: 0
}
```
or just
```
> SMPPEX.Pdu.Factory.bind_transmitter("system_id", "password", %{interface_version: 0x34})
%SMPPEX.Pdu{
  command_id: 2,
  command_status: 0,
  mandatory: %{
    interface_version: 52,
    password: "password",
    system_id: "system_id"
  },
  optional: %{},
  ref: #Reference<0.4205070554.1013710852.169021>,
  sequence_number: 0
}
```

**Comment by Menkir** [comment]
@savonarola The second variant worked. Thank you!
